---
title: "simulations_hi1.Rmd"
author: "Dany Chauvin"
date: '2022-12-06'
output: html_document
---

```{r}
source("./mother_machine_experiments_toolbox/load_functions_and_packages.R")
denoised_data_files_folder <- "/scicore/home/nimwegen/rocasu25/Documents/Projects/biozentrum/gfp_fluctuations_project/inference_on_experimental_data/inference_20221202114805"
correlation_data_folder <- "/scicore/home/nimwegen/rocasu25/Documents/Projects/biozentrum/gfp_fluctuations_project/inference_on_experimental_data/correlations2"
myframes_final <- readr::read_csv("./denoised_data_hi1_all_conditions_20221202/hi1_allconditions_final.csv")
```

# Import correlation data

```{r}
list_of_corr_files <- lapply(correlation_data_folder,function(.l){
  list.files(path=.l,pattern="correlations.csv$",recursive = TRUE,full.names=TRUE)}) %>% 
  unlist()

df_of_data_files <- tibble(path=list_of_corr_files) %>% 
    tidyr::extract(path,"condition","([0-9a-z]{1,})_[0-9a-zA-Z]{1,}_[0-9]{8}_[a-z0-9]{1,}_b_correlations.csv$",remove=FALSE,convert=FALSE) %>% 
    tidyr::extract(path,"promoter","[0-9a-z]{1,}_([0-9a-zA-Z]{1,})_[0-9]{8}_[a-z0-9]{1,}_b_correlations.csv$",remove=FALSE,convert=FALSE) %>% 
  rename(raw_curated_data_path=path) %>% 
  tidyr::extract(condition,"carbon_source_concentration","^[a-z]{1,}0([0-9]{2})",remove=FALSE,convert=FALSE) %>% 
  mutate(carbon_source_concentration=as.double(carbon_source_concentration)/100) %>% 
  tidyr::extract(condition,"carbon_source","^([a-z]{1,})0[0-9]{2}",remove=FALSE,convert=FALSE)

correlations_df <- df_of_data_files %>% 
  ungroup() %>% 
  distinct(raw_curated_data_path) %>% 
  .$raw_curated_data_path %>% 
  lapply(function(.l) readr::read_csv(.l) %>% 
  mutate(raw_curated_data_path=.l)) %>% 
  do.call(rbind, .) %>% 
  left_join(df_of_data_files,by=c("raw_curated_data_path"))

correlations_df <- correlations_df %>% 
  rename(cov_l_l="cov_l(t+dt)l(t)",
         cov_l_l_err="cov_l(t+dt)l(t)_err",
         col_q_q="cov_q(t+dt)q(t)",
         cov_q_q_err="cov_q(t+dt)q(t)_err",
         cov_q_l="cov_q(t+dt)l(t)",
         cov_q_l_err="cov_q(t+dt)l(t)_err",
         cov_l_q="cov_l(t+dt)q(t)",
         cov_l_q_err="cov_l(t+dt)q(t)_err",
         cov_c_c="cov_c(t+dt)c(t)",
         cov_c_c_err="cov_c(t+dt)c(t)_err",
         corr_l_l="corr_l(t+dt)l(t)",
         corr_l_l_err="corr_l(t+dt)l(t)_err",
         corr_q_q="corr_q(t+dt)q(t)",
         corr_q_q_err="corr_q(t+dt)q(t)_err",
         corr_q_l="corr_q(t+dt)l(t)",
         corr_q_l_err="corr_q(t+dt)l(t)_err",
         corr_l_q="corr_l(t+dt)q(t)",
         corr_l_q_err="corr_l(t+dt)q(t)_err",
         corr_c_c="corr_c(t+dt)c(t)",
         corr_c_c_err="corr_c(t+dt)c(t)_err",
         corr_naive_l_l="corr_naive_l(t+dt)l(t)",
         corr_naive_l_q="corr_naive_l(t+dt)q(t)",
         corr_naive_q_l="corr_naive_q(t+dt)l(t)",
         corr_naive_q_q="corr_naive_q(t+dt)q(t)",
         corr_naive_c_c="corr_naive_c(t+dt)c(t)")

#correlations_df$condition <- factor(correlations_df$condition,levels=c("acetate005","acetate020","glycerol040","glucose020","glucoseaa020"))
```

# Detemine mean doubling time

```{r}
mean_doubling_time_df <- myframes_final %>%
  group_by(cell) %>% 
  sample_n(1) %>% 
  ungroup() %>% 
  group_by(condition) %>% 
  mutate(mean_doubling_time=1/mean(lambda/log(2))) %>% 
  ungroup() %>% 
  distinct(condition,mean_doubling_time)

```

# Compare these correlations together with OU processes

```{r}
#Import parameters first
gamma_lambda_df <- myparameters %>% 
  filter(name=="gamma_lambda") %>% 
  select(condition,final) %>% 
  #mutate(final=final) %>% 
  rename(gamma_lambda=final) %>% 
  left_join(mean_doubling_time_df,by=c("condition")) %>% 
  mutate(gamma_lambda_normalized=gamma_lambda*mean_doubling_time) %>% 
  select(condition,gamma_lambda,gamma_lambda_normalized)

gamma_lambda_err_df <- myerrors %>% 
  filter(epsilon==0.05) %>% 
  mutate(gamma_lambda_err=sqrt(gamma_lambda)) %>% 
  select(gamma_lambda_err,condition)

correlations_df %>%
  left_join(mean_doubling_time_df,by=c("condition")) %>% 
  left_join(gamma_lambda_df,by=c("condition")) %>% 
  left_join(gamma_lambda_err_df,by=c("condition")) %>% 
  mutate(condition=factor(condition,levels=c("acetate005","acetate020","glycerol040","glucose020","glucoseaa020"))) %>% 
  mutate(dt_norm=dt/mean_doubling_time) %>% 
  mutate(corr_OU=exp(-gamma_lambda*dt),
         corr_OU_min=exp(-(gamma_lambda+gamma_lambda_err)*dt),
         corr_OU_max=exp(-(gamma_lambda-gamma_lambda_err)*dt)) %>%
  filter(dt_norm<3) %>% 
  ggplot()+
  geom_line(aes(dt_norm,corr_l_l,col=condition))+
  geom_ribbon(aes(x=dt_norm,y=corr_l_l,ymin=corr_l_l-corr_l_l_err,ymax=corr_l_l+corr_l_l_err,fill=condition),alpha=0.2)+
  geom_line(aes(dt_norm,corr_OU,col=condition),linetype="dashed")+
  geom_ribbon(aes(x=dt_norm,y=corr_OU,ymin=corr_OU_min,ymax=corr_OU_max,fill=condition),alpha=0.2)+
  theme_cowplot()+
  scale_y_continuous(trans="log10",limits=c(0.1,1))+
  annotation_logticks(sides = "l") + 
  xlim(c(0,3))+
  #ylim(c(0,1))+
  coord_cartesian(ylim=c(0.1115,1))+
  xlab("dt / mean doubing time")+
  ylab("Correlation l(t+dt),l(t)")

ggsave("./20221208_presentation/l_l_autocorrelation_function.pdf",width=7,height=4)
```
# Production autocorrelation function

```{r}
#Import parameters first
gamma_q_df <- myparameters %>% 
  filter(name=="gamma_q") %>% 
  select(condition,final) %>% 
  #mutate(final=final) %>% 
  rename(gamma_q=final) %>% 
  left_join(mean_doubling_time_df,by=c("condition")) %>% 
  mutate(gamma_q_normalized=gamma_q*mean_doubling_time) %>% 
  select(condition,gamma_q,gamma_q_normalized)

gamma_q_err_df <- myerrors %>% 
  filter(epsilon==0.05) %>% 
  mutate(gamma_q_err=sqrt(gamma_q)) %>% 
  select(gamma_q_err,condition)

correlations_df %>%
  left_join(mean_doubling_time_df,by=c("condition")) %>% 
  left_join(gamma_q_df,by=c("condition")) %>% 
  left_join(gamma_q_err_df,by=c("condition")) %>% 
  mutate(condition=factor(condition,levels=c("acetate005","acetate020","glycerol040","glucose020","glucoseaa020"))) %>% 
  mutate(dt_norm=dt/mean_doubling_time) %>% 
  mutate(corr_OU=exp(-gamma_q*dt),
         corr_OU_min=exp(-(gamma_q+gamma_q_err)*dt),
         corr_OU_max=exp(-(gamma_q-gamma_q_err)*dt)) %>%
  filter(dt_norm<1) %>% 
  ggplot()+
  geom_line(aes(dt_norm,corr_q_q,col=condition))+
  geom_ribbon(aes(x=dt_norm,y=corr_q_q,ymin=corr_q_q-corr_q_q_err,ymax=corr_q_q+corr_q_q_err,fill=condition),alpha=0.2)+
  geom_line(aes(dt_norm,corr_OU,col=condition),linetype="dashed")+
  geom_ribbon(aes(x=dt_norm,y=corr_OU,ymin=corr_OU_min,ymax=corr_OU_max,fill=condition),alpha=0.2)+
  theme_cowplot()+
  scale_y_continuous(trans="log10",limits=c(0.1,1))+
  annotation_logticks(sides = "l") + 
  xlim(c(0,1))+
  #ylim(c(0,1))+
  coord_cartesian(ylim=c(0.1115,1))+
  xlab("dt / mean doubing time")+
  ylab("Correlation q(t+dt),q(t)")

ggsave("./20221208_presentation/q_q_autocorrelation_function.pdf",width=7,height=4)

```

# Correlation between q(t+dt) and l(t)

```{r}
#Import parameters first
correlations_df %>%
  left_join(mean_doubling_time_df,by=c("condition")) %>% 
  mutate(condition=factor(condition,levels=c("acetate005","acetate020","glycerol040","glucose020","glucoseaa020"))) %>% 
  mutate(dt_norm=dt/mean_doubling_time) %>% 
    filter(dt_norm<3) %>% 
  ggplot()+
  geom_line(aes(dt_norm,corr_q_l,col=condition))+
  geom_ribbon(aes(x=dt_norm,y=corr_q_l,ymin=corr_q_l-corr_q_l_err,ymax=corr_q_l+corr_q_l_err,fill=condition),alpha=0.2)+
  #geom_line(aes(dt_norm,corr_OU,col=condition),linetype="dashed")+
  #geom_ribbon(aes(x=dt_norm,y=corr_OU,ymin=corr_OU_min,ymax=corr_OU_max,fill=condition),alpha=0.2)+
  theme_cowplot()+
  #scale_y_continuous(trans="log10",limits=c(0.1,1))+
  #annotation_logticks(sides = "l") + 
  #xlim(c(0,1))+
  #ylim(c(0,1))+
  #coord_cartesian(ylim=c(0.1115,1))+
  xlab("dt / mean doubing time")+
  ylab("Correlation q(t+dt),l(t)")

ggsave("./20221208_presentation/q_l_correlation_function.pdf",width=7,height=4)
```

# Correlation between q(t) and l(t+dt)

```{r}
#Import parameters first
correlations_df %>%
  left_join(mean_doubling_time_df,by=c("condition")) %>% 
  mutate(condition=factor(condition,levels=c("acetate005","acetate020","glycerol040","glucose020","glucoseaa020"))) %>% 
  mutate(dt_norm=dt/mean_doubling_time) %>% 
    filter(dt_norm<3) %>% 
  ggplot()+
  geom_line(aes(dt_norm,corr_l_q,col=condition))+
  geom_ribbon(aes(x=dt_norm,y=corr_l_q,ymin=corr_l_q-corr_l_q_err,ymax=corr_l_q+corr_l_q_err,fill=condition),alpha=0.2)+
  #geom_line(aes(dt_norm,corr_OU,col=condition),linetype="dashed")+
  #geom_ribbon(aes(x=dt_norm,y=corr_OU,ymin=corr_OU_min,ymax=corr_OU_max,fill=condition),alpha=0.2)+
  theme_cowplot()+
  #scale_y_continuous(trans="log10",limits=c(0.1,1))+
  #annotation_logticks(sides = "l") + 
  #xlim(c(0,1))+
  #ylim(c(0,1))+
  #coord_cartesian(ylim=c(0.1115,1))+
  xlab("dt / mean doubing time")+
  ylab("Correlation l(t+dt),q(t)")

ggsave("./20221208_presentation/l_q_autocorrelation_function.pdf",width=7,height=4)

```

# Concentration correlation

```{r}
#Import parameters first
correlations_df %>%
  left_join(mean_doubling_time_df,by=c("condition")) %>% 
  mutate(condition=factor(condition,levels=c("acetate005","acetate020","glycerol040","glucose020","glucoseaa020"))) %>% 
  mutate(dt_norm=dt/mean_doubling_time) %>% 
    filter(dt_norm<4) %>% 
  ggplot()+
  geom_line(aes(dt_norm,corr_c_c,col=condition))+
  geom_ribbon(aes(x=dt_norm,y=corr_c_c,ymin=corr_c_c-corr_c_c_err,ymax=corr_c_c+corr_c_c_err,fill=condition),alpha=0.2)+
  theme_cowplot()+
  ylim(c(0,1))+
  xlab("dt / mean doubing time")+
  ylab("Correlation c(t+dt),c(t)")

ggsave("./20221208_presentation/c_c_autocorrelation_function.pdf",width=7,height=4)

```
